#!/bin/bash

dir="$(dirname "$(readlink -f "$0")")"
name="$(basename "$0")"
jar="$dir/$name.jar"

export GOOGLE_APPLICATION_CREDENTIALS="${GOOGLE_APPLICATION_CREDENTIALS:-$HOME/.config/gcloud/application_default_credentials.json}"

java -jar "$jar" "$@"
